name: build
on: [workflow_dispatch]

jobs:
  VCPKG:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
        include:
          - os: 'ubuntu-latest'
            mono: 'mono'
            triplet: 'x64-linux'
            exe_ext: ''
            build_dir: ninja-vcpkg
          - os: 'windows-2022'
            mono: ''
            triplet: 'x64-win'
            exe_ext: '.exe'
            build_dir: vs-vcpkg
          - os: 'macos-latest'
            mono: 'mono'
            triplet: 'x64-osx'
            exe_ext: ''
            build_dir: ninja-vcpkg

    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

    steps:
      - name: 'Remove old VCPKG'
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        shell: 'bash'
        run: sudo rm -rf "$VCPKG_INSTALLATION_ROOT"

      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: lukka/get-cmake@latest

      - name: Setup MacOS
        if: startsWith(matrix.os, 'macOS')
        run: brew install automake autoconf ninja cmake

      - name: Setup Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt upgrade && sudo apt install
          build-essential gperf ninja-build cmake
          libgl1-mesa-dev
          libfontconfig1-dev
          libfreetype6-dev
          libx11-dev
          libx11-xcb-dev
          libxcb-damage0-dev
          libxcb-dpms0-dev
          libxcb-glx0-dev
          libxcb-icccm4-dev
          libxcb-image0-dev
          libxcb-keysyms1-dev
          libxcb-present-dev
          libxcb-randr0-dev
          libxcb-record0-dev
          libxcb-render-util0-dev
          libxcb-render0-dev
          libxcb-res0-dev
          libxcb-shape0-dev
          libxcb-shm0-dev
          libxcb-sync-dev
          libxcb-util-dev
          libxcb-xfixes0-dev
          libxcb-xinerama0-dev
          libxcb-xkb-dev
          libxcb1-dev
          libxext-dev
          libxfixes-dev
          libxi-dev
          libxkbcommon-dev
          libxkbcommon-x11-dev
          libxrender-dev
          libatspi2.0-dev

      - uses: nuget/setup-nuget@v1

      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        run: >
          nuget sources add
          -source "https://nuget.pkg.github.com/free-audio/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "free-audio"
          -password "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Bootstrap VCPKG'
        shell: bash
        run: vcpkg/bootstrap-vcpkg.sh

      - name: Build
        shell: bash
        run: scripts/build.sh

      - name: Archive artifact
        shell: bash
        run: tar -cvJf clap-plugins.clap.tar.xz --strip-components 4 builds/${{matrix.build_dir}}/plugins/Release/clap-plugins.clap

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: clap-plugins-${{ matrix.triplet }}.tar.xz
          path: clap-plugins.clap.tar.xz